<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Контакты");
?><?$APPLICATION->IncludeComponent(
	"bitrix:map.google.view",
	"contacts",
	Array(
		"ADD_CONTAINER" => "N",
		"ADD_SECTION" => "Y",
		"API_KEY" => "",
		"BLOCK_NAME_IS_LINK" => "N",
		"COMPONENT_TEMPLATE" => "contacts",
		"CONTROLS" => array(),
		"INIT_MAP_TYPE" => "ROADMAP",
		"MAP_DATA" => "a:4:{s:10:\"google_lat\";d:55.7383;s:10:\"google_lon\";d:37.5946;s:12:\"google_scale\";i:13;s:10:\"PLACEMARKS\";a:1:{i:0;a:3:{s:4:\"TEXT\";s:19:\"Центральный магазин\";s:3:\"LON\";d:37.61760262451173;s:3:\"LAT\";d:55.7392180772006;}}}",
		"MAP_HEIGHT" => "500",
		"MAP_ID" => "",
		"MAP_WIDTH" => "600",
		"OPTIONS" => array(),
		"PARENT_TITLE" => "Карта",
		"RS_LIST_SECTION" => "l_section",
		"RS_LIST_SECTION_ADD_CONTAINER" => "Y",
		"RS_LIST_SECTION_BUTTON_LINK" => "",
		"RS_LIST_SECTION_BUTTON_NAME" => "",
		"RS_LIST_SECTION_SHOW_BUTTON" => "N",
		"RS_LIST_SECTION_SHOW_TITLE" => "N",
		"SHOW_PARENT_TITLE" => "N"
	)
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:main.include",
	"ask_question",
	Array(
		"AREA_FILE_SHOW" => "file",
		"BLOCK_TYPE" => "wide",
		"BTN_LINK" => "#SITE_DIR#forms/ask/",
		"BTN_TEXT" => "Задать вопрос",
		"COMPONENT_TEMPLATE" => "ask_question",
		"EDIT_TEMPLATE" => "",
		"PATH" => "#SITE_DIR#include/common/ask_question.php",
		"RS_ASK_B24_CRM_FORM_ID" => "",
		"RS_ASK_B24_CRM_FORM_SEC" => "",
		"RS_ASK_B24_CRM_FORM_USE" => "N",
		"TEMPLATE" => "line"
	)
);?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"staff",
	Array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_CONTAINER" => "N",
		"ADD_SECTION" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ASK_LINK" => "#SITE_DIR#forms/ask_staff/?element_id=#ELEMENT_ID#",
		"BLOCK_NAME_IS_LINK" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "staff",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "#CONTENT_STAFF_IBLOCK_ID#",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "4",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "bootstrap",
		"PAGER_TITLE" => "",
		"PARENT_SECTION" => "77",
		"PARENT_SECTION_CODE" => "otdel-prodazh",
		"PARENT_TITLE" => "Отдел продаж",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0=>"NAME",1=>"POSITION",2=>"DESCRIPTION",3=>"CONTACTS",4=>"SOCIALS",5=>"IS_ASK",6=>"",),
		"PROP_CONTACTS" => "CONTACTS",
		"PROP_DESCRIPTION" => "DESCRIPTION",
		"PROP_IS_ASK" => "IS_ASK",
		"PROP_NAME" => "NAME",
		"PROP_POSITION" => "POSITION",
		"PROP_SOCIAL" => "SOCIALS",
		"RS_LIST_SECTION" => "l_section",
		"RS_LIST_SECTION_ADD_CONTAINER" => "Y",
		"RS_LIST_SECTION_BUTTON_LINK" => "",
		"RS_LIST_SECTION_BUTTON_NAME" => "",
		"RS_LIST_SECTION_SHOW_BUTTON" => "N",
		"RS_LIST_SECTION_SHOW_TITLE" => "Y",
		"RS_LIST_SECTION_TITLE" => "Отдел продаж",
		"RS_TEMPLATE" => "type1",
		"SECTION_PAGE_URL" => "",
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SHOW_DESCRIPTION" => "N",
		"SHOW_PARENT_TITLE" => "Y",
		"SHOW_TITLE" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N"
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>